name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Install dependencies"
      run: |
       sudo apt update
       sudo apt install libpng-dev libsdl2-dev libsdl2-ttf-dev
       wget http://mirrors.kernel.org/ubuntu/pool/universe/l/lua5.4/liblua5.4-0_5.4.0-2_amd64.deb
       sudo dpkg -i liblua5.4-0_5.4.0-2_amd64.deb
       wget http://mirrors.kernel.org/ubuntu/pool/universe/l/lua5.4/liblua5.4-dev_5.4.0-2_amd64.deb
       sudo dpkg -i liblua5.4-dev_5.4.0-2_amd64.deb
    - name: "Build"
      run: |
       UNIT_TEST=1 make -j
    - name: "Run"
      run: |
       bin/main

  build_windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: msys2/setup-msys2@v2
      with:
        install: gcc mingw-w64-x86_64-make mingw-w64-x86_64-cmake mingw64/mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-libpng mingw64/mingw-w64-x86_64-freeglut mingw64/mingw-w64-x86_64-glew mingw64/mingw-w64-x86_64-lua
    - name: "Build"
      run: |
       cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -B$Env:GITHUB_WORKSPACE/build -G "MinGW Makefiles"
       cmake --build $Env:GITHUB_WORKSPACE/build --config Debug --target all -j 10

